name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # cada 10 minutos (UTC)
  workflow_dispatch:         # permite ejecutarlo manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint
        run: |
          curl -fsS https://maya-verification.onrender.com/health >/dev/null || true
